version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.app
    container_name: pms_web
    command: python3 manage.py runserver  --insecure 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/usr/src/app/
      - ./host_to_container_pipe:/hostpipe
    ports:
      - 8888:8000
    env_file:
      - ./.env
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: pms_db
    volumes:
      - ./database:/var/lib/postgresql/data/
      - ./db_backup:/home/db_backup/
    environment:
      - POSTGRES_USER=pms
      - POSTGRES_PASSWORD=pms
      - POSTGRES_DB=pms
    ports:
      - 7777:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pms"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
